const artist = {
  easyId: "davinci",
  imageMaxName: "ARTIST_MAX_DAVINCI.jpg",
  imageMaxWidth: 1286,
  imageMaxHeight: 1842,
  imageOptName: "ARTIST_OPT_DAVINCI.jpg",
  imageOptWidth: 1286,
  imageOptHeight: 1842,
  imageThmName: "ARTIST_THM_DAVINCI.webp",
  imageThmWidth: 335,
  imageThmHeight: 480,
  isPublished: true,
  birthName: "Lionardo di ser Piero da Vinci",
  commonName: "Leonardo da Vinci",
  dateOfBirth: "c1452-04-14x1452-04-15",
  dateOfBirthAccuracy: "Circa, Between Days",
  dateOfDeath: "a1519-05-02",
  dateOfDeathAccuracy: "Accepted",
  nationality: "Italian",
  knownFor: "[Painting, Drawing, Sculpting, Science, Engineering, Architecture, Anatomy]",
  movements: "[]",
  gender: "male",
  deceased: true,
  birthCountry: "Italy",
  birthLocation: "Vinci, Republic of Florence",
  birthLocationDetails: "City, Republic",
  deathCountry: "France",
  deathLocation: "Amboise",
  deathLocationDetails: "Commune, City",
  wikiPage: "https://en.wikipedia.org/wiki/Leonardo_da_Vinci",
  wikiPhoto: "https://en.wikipedia.org/wiki/File:Francesco_Melzi_-_Portrait_of_Leonardo.png",
  imageLink:
    "https://upload.wikimedia.org/wikipedia/commons/c/cb/Francesco_Melzi_-_Portrait_of_Leonardo.png",
};

const location = {
  easyId: "louvre",
  imageMaxName: "LOCATION_MAX_LOUVRE.jpg",
  imageMaxWidth: 3048,
  imageMaxHeight: 1209,
  imageOptName: "LOCATION_OPT_LOUVRE.jpg",
  imageOptWidth: 1920,
  imageOptHeight: 762,
  imageThmName: "LOCATION_THM_LOUVRE.webp",
  imageThmWidth: 480,
  imageThmHeight: 190,
  isPublished: true,
  name: "Musée du Louvre",
  nickname: "Louvre",
  dateFirstOpened: "a1793",
  streetAddress: "Rue de Rivoli",
  city: "Paris",
  state: "Ile De France Region",
  postalCode: "75001",
  country: "France",
  coorN: 488606111,
  coorE: 23354553,
  website: "www.louvre.fr",
  wikiPage: "https://en.wikipedia.org/wiki/Louvre",
  wikiPhoto: "https://en.wikipedia.org/wiki/File:Louvre_2007_02_24_c.jpg",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/0/00/Louvre_2007_02_24_c.jpg",
};

const artwork = {
  easyId: "davinci_0001",
  imageMaxName: "WORK_MAX_DAVINCI_0001.jpg",
  imageMaxWidth: 7479,
  imageMaxHeight: 11146,
  imageOptName: "WORK_OPT_DAVINCI_0001.jpg",
  imageOptWidth: 1288,
  imageOptHeight: 1920,
  imageThmName: "WORK_THM_DAVINCI_0001.webp",
  imageThmWidth: 322,
  imageThmHeight: 480,
  isPublished: true,
  artist: "{ 'connect': { 'easyId': 'davinci' } }",
  artworkLocation: "{ 'connect': { 'easyId': 'louvre' } }",
  artworkLocationURL:
    "https://www.louvre.fr/oeuvre-notices/portrait-de-lisa-gherardini-epouse-de-francesco-del-giocondo",
  fileName: "DaVinci - Mona Lisa [] [Louvre]",
  workName: "Mona Lisa",
  workName_english: "Mona Lisa",
  workName_ascii: "Mona Lisa",
  dateCompleted: "c 1503-1506, 1517",
  dateCompletedAccuracy: "circa, possible touch-up",
  type: "Painting",
  genre: "portrait",
  medium: "Oil",
  mediumSupport: "poplar panel",
  description: `Lisa Gherardini, wife of Francesco Giocondo
The history of the Mona Lisa is shrouded in mystery. Among the aspects which remain unclear are the exact identity of the sitter, who commissioned the portrait, how long Leonardo worked on the painting, how long he kept it, and how it came to be in the French royal collection.
The portrait may have been painted to mark one of two events - either when Francesco del Giocondo and his wife bought their own house in 1503, or when their second son, Andrea, was born in December 1502 after the death of a daughter in 1499. The delicate dark veil that covers Mona Lisa's hair is sometimes considered a mourning veil. In fact, such veils were commonly worn as a mark of virtue. Her clothing is unremarkable. Neither the yellow sleeves of her gown, nor her pleated gown, nor the scarf delicately draped round her shoulders are signs of aristocratic status.

A new artistic formula
The Mona Lisa is the earliest Italian portrait to focus so closely on the sitter in a half-length portrait. The painting is generous enough in its dimensions to include the arms and hands without them touching the frame. The portrait is painted to a realistic scale in the highly structured space where it has the fullness of volume of a sculpture in the round. The figure is shown in half-length, from the head to the waist, sitting in a chair whose arm is resting on balusters. She is resting her left arm on the arm of the chair, which is placed in front of a loggia, suggested by the parapet behind her and the two fragmentary columns framing the figure and forming a ""window"" looking out over the landscape. The perfection of this new artistic formula explains its immediate influence on Florentine and Lombard art of the early 16th century. Such aspects of the work as the three-quarter view of a figure against a landscape, the architectural setting, and the hands joined in the foreground were already extant in Flemish portraiture of the second half of the 15th century, particularly in the works of Hans Memling. However, the spacial coherence, the atmospheric illusionism, the monumentality, and the sheer equilibrium of the work were all new. In fact, these aspects were also new to Leonardo's work, as none of his earlier portraits display such controlled majesty.

An emblematic smile
The Mona Lisa's famous smile represents the sitter in the same way that the juniper branches represent Ginevra Benci and the ermine represents Cecilia Gallerani in their portraits, in Washington and Krakow respectively. It is a visual representation of the idea of happiness suggested by the word ""gioconda"" in Italian. Leonardo made this notion of happiness the central motif of the portrait: it is this notion which makes the work such an ideal. The nature of the landscape also plays a role. The middle distance, on the same level as the sitter's chest, is in warm colors. Men live in this space: there is a winding road and a bridge. This space represents the transition between the space of the sitter and the far distance, where the landscape becomes a wild and uninhabited space of rocks and water which stretches to the horizon, which Leonardo has cleverly drawn at the level of the sitter's eyes.`,
  descriptionSource: "www.louvre.fr",
  otherDescription: "Subject: Lisa Gherardini",
  accession: "779",
  creditLine: "Acquired by François I in 1518",
  dimensionCoreW_mm: 530,
  dimensionCoreH_mm: 770,
  dimensionCoreD_mm: 0,
  dimensionCoreWHD_in: "21 x 30 in",
  dimensionFramedW_mm: 795,
  dimensionFramedH_mm: 1155,
  dimensionFramedD_mm: 25,
  dimensionFramedWHD_in: "31 1/4 x 45 1/2 x 0 1/8 in; made up",
  signature: "No signature or date",
  onviewAt: "On view in Salle des États: Denon wing - 1st floor - Room 711 - Mona Lisa room",
  wikiPage: "https://en.wikipedia.org/wiki/Mona_Lisa",
  wikiPhoto: "Wiki",
  imageLink:
    "https://en.wikipedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
};

export { artwork, artist, location };
